config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/result'

  resources :post_code_electorate_maps
  resources :member_of_parliaments
  resources :electorates
  resources :post_codes

  root 'home#index'

end

app/models/member_of_parliament.rb
class MemberOfParliament < ActiveRecord::Base
  belongs_to :electorate
end

app/controllers/member_of_parliaments_controller.rb
class MemberOfParliamentsController < ApplicationController
  before_action :set_member_of_parliament, only: [:show, :edit, :update, :destroy]

  # GET /member_of_parliaments
  # GET /member_of_parliaments.json
  def index
    @member_of_parliaments = MemberOfParliament.all
  end

  # GET /member_of_parliaments/1
  # GET /member_of_parliaments/1.json
  def show
  end

  # GET /member_of_parliaments/new
  def new
    @member_of_parliament = MemberOfParliament.new
  end

  # GET /member_of_parliaments/1/edit
  def edit
  end

  # POST /member_of_parliaments
  # POST /member_of_parliaments.json
  def create
    @member_of_parliament = MemberOfParliament.new(member_of_parliament_params)

    respond_to do |format|
      if @member_of_parliament.save
        format.html { redirect_to @member_of_parliament, notice: 'Member of parliament was successfully created.' }
        format.json { render :show, status: :created, location: @member_of_parliament }
      else
        format.html { render :new }
        format.json { render json: @member_of_parliament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_of_parliaments/1
  # PATCH/PUT /member_of_parliaments/1.json
  def update
    respond_to do |format|
      if @member_of_parliament.update(member_of_parliament_params)
        format.html { redirect_to @member_of_parliament, notice: 'Member of parliament was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_of_parliament }
      else
        format.html { render :edit }
        format.json { render json: @member_of_parliament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_of_parliaments/1
  # DELETE /member_of_parliaments/1.json
  def destroy
    @member_of_parliament.destroy
    respond_to do |format|
      format.html { redirect_to member_of_parliaments_url, notice: 'Member of parliament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_of_parliament
      @member_of_parliament = MemberOfParliament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_of_parliament_params
      params.require(:member_of_parliament).permit(:first_name, :last_name, :email, :electorate_id)
    end
end

app/helpers/member_of_parliaments_helper.rb
module MemberOfParliamentsHelper
end

app/views/member_of_parliaments/_form.html.erb
<%= form_for(@member_of_parliament) do |f| %>
  <% if @member_of_parliament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_of_parliament.errors.count, "error") %> prohibited this member_of_parliament from being saved:</h2>

      <ul>
      <% @member_of_parliament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :electorate_id %><br>
    <%= f.text_field :electorate_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/member_of_parliaments/edit.html.erb
<h1>Editing Member Of Parliament</h1>

<%= render 'form' %>

<%= link_to 'Show', @member_of_parliament %> |
<%= link_to 'Back', member_of_parliaments_path %>

app/views/member_of_parliaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Member Of Parliaments</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Electorate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @member_of_parliaments.each do |member_of_parliament| %>
      <tr>
        <td><%= member_of_parliament.first_name %></td>
        <td><%= member_of_parliament.last_name %></td>
        <td><%= member_of_parliament.email %></td>
        <td><%= member_of_parliament.electorate.name %></td>
        <td><%= link_to 'Show', member_of_parliament %></td>
        <td><%= link_to 'Edit', edit_member_of_parliament_path(member_of_parliament) %></td>
        <td><%= link_to 'Destroy', member_of_parliament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member of parliament', new_member_of_parliament_path %>

app/views/member_of_parliaments/new.html.erb
<h1>New Member Of Parliament</h1>

<%= render 'form' %>

<%= link_to 'Back', member_of_parliaments_path %>

app/views/member_of_parliaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member_of_parliament.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member_of_parliament.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member_of_parliament.email %>
</p>

<p>
  <strong>Electorate:</strong>
  <%= @member_of_parliament.electorate %>
</p>

<%= link_to 'Edit', edit_member_of_parliament_path(@member_of_parliament) %> |
<%= link_to 'Back', member_of_parliaments_path %>