config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/result'

  resources :post_code_electorate_maps
  resources :member_of_parliaments
  resources :electorates
  resources :post_codes

  root 'home#index'

end

app/models/electorate.rb
class Electorate < ActiveRecord::Base
    has_many :member_of_parliaments
end

app/controllers/electorates_controller.rb
class ElectoratesController < ApplicationController
  before_action :set_electorate, only: [:show, :edit, :update, :destroy]

  # GET /electorates
  # GET /electorates.json
  def index
    @electorates = Electorate.all
  end

  # GET /electorates/1
  # GET /electorates/1.json
  def show
  end

  # GET /electorates/new
  def new
    @electorate = Electorate.new
  end

  # GET /electorates/1/edit
  def edit
  end

  # POST /electorates
  # POST /electorates.json
  def create
    @electorate = Electorate.new(electorate_params)

    respond_to do |format|
      if @electorate.save
        format.html { redirect_to @electorate, notice: 'Electorate was successfully created.' }
        format.json { render :show, status: :created, location: @electorate }
      else
        format.html { render :new }
        format.json { render json: @electorate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /electorates/1
  # PATCH/PUT /electorates/1.json
  def update
    respond_to do |format|
      if @electorate.update(electorate_params)
        format.html { redirect_to @electorate, notice: 'Electorate was successfully updated.' }
        format.json { render :show, status: :ok, location: @electorate }
      else
        format.html { render :edit }
        format.json { render json: @electorate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electorates/1
  # DELETE /electorates/1.json
  def destroy
    @electorate.destroy
    respond_to do |format|
      format.html { redirect_to electorates_url, notice: 'Electorate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_electorate
      @electorate = Electorate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def electorate_params
      params.require(:electorate).permit(:name)
    end
end

app/helpers/electorates_helper.rb
module ElectoratesHelper
end

app/views/electorates/_form.html.erb
<%= form_for(@electorate) do |f| %>
  <% if @electorate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@electorate.errors.count, "error") %> prohibited this electorate from being saved:</h2>

      <ul>
      <% @electorate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/electorates/edit.html.erb
<h1>Editing Electorate</h1>

<%= render 'form' %>

<%= link_to 'Show', @electorate %> |
<%= link_to 'Back', electorates_path %>

app/views/electorates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Electorates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @electorates.each do |electorate| %>
      <tr>
        <td><%= electorate.name %></td>
        <td><%= link_to 'Show', electorate %></td>
        <td><%= link_to 'Edit', edit_electorate_path(electorate) %></td>
        <td><%= link_to 'Destroy', electorate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Electorate', new_electorate_path %>

app/views/electorates/new.html.erb
<h1>New Electorate</h1>

<%= render 'form' %>

<%= link_to 'Back', electorates_path %>

app/views/electorates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @electorate.name %>
</p>

<%= link_to 'Edit', edit_electorate_path(@electorate) %> |
<%= link_to 'Back', electorates_path %>