config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/result'

  resources :post_code_electorate_maps
  resources :member_of_parliaments
  resources :electorates
  resources :post_codes

  root 'home#index'

end

app/models/post_code.rb
class PostCode < ActiveRecord::Base
    has_many :post_code_electorate_maps
end

app/controllers/post_codes_controller.rb
class PostCodesController < ApplicationController
  before_action :set_post_code, only: [:show, :edit, :update, :destroy]

  # GET /post_codes
  # GET /post_codes.json
  def index
    @post_codes = PostCode.all
  end

  # GET /post_codes/1
  # GET /post_codes/1.json
  def show
  end

  # GET /post_codes/new
  def new
    @post_code = PostCode.new
  end

  # GET /post_codes/1/edit
  def edit
  end

  # POST /post_codes
  # POST /post_codes.json
  def create
    @post_code = PostCode.new(post_code_params)

    respond_to do |format|
      if @post_code.save
        format.html { redirect_to @post_code, notice: 'Post code was successfully created.' }
        format.json { render :show, status: :created, location: @post_code }
      else
        format.html { render :new }
        format.json { render json: @post_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_codes/1
  # PATCH/PUT /post_codes/1.json
  def update
    respond_to do |format|
      if @post_code.update(post_code_params)
        format.html { redirect_to @post_code, notice: 'Post code was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_code }
      else
        format.html { render :edit }
        format.json { render json: @post_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_codes/1
  # DELETE /post_codes/1.json
  def destroy
    @post_code.destroy
    respond_to do |format|
      format.html { redirect_to post_codes_url, notice: 'Post code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_code
      @post_code = PostCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_code_params
      params.require(:post_code).permit(:code)
    end
end

app/helpers/post_codes_helper.rb
module PostCodesHelper
end

app/views/post_codes/_form.html.erb
<%= form_for(@post_code) do |f| %>
  <% if @post_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_code.errors.count, "error") %> prohibited this post_code from being saved:</h2>

      <ul>
      <% @post_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_codes/edit.html.erb
<h1>Editing Post Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_code %> |
<%= link_to 'Back', post_codes_path %>

app/views/post_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Codes</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_codes.each do |post_code| %>
      <tr>
        <td><%= post_code.code %></td>
        <td><%= link_to 'Show', post_code %></td>
        <td><%= link_to 'Edit', edit_post_code_path(post_code) %></td>
        <td><%= link_to 'Destroy', post_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post code', new_post_code_path %>

app/views/post_codes/new.html.erb
<h1>New Post Code</h1>

<%= render 'form' %>

<%= link_to 'Back', post_codes_path %>

app/views/post_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @post_code.code %>
</p>

<%= link_to 'Edit', edit_post_code_path(@post_code) %> |
<%= link_to 'Back', post_codes_path %>