config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/result'

  resources :post_code_electorate_maps
  resources :member_of_parliaments
  resources :electorates
  resources :post_codes

  root 'home#index'

end

app/models/post_code_electorate_map.rb
class PostCodeElectorateMap < ActiveRecord::Base
  belongs_to :electorate
  belongs_to :post_code
end

app/controllers/post_code_electorate_maps_controller.rb
class PostCodeElectorateMapsController < ApplicationController
  before_action :set_post_code_electorate_map, only: [:show, :edit, :update, :destroy]

  # GET /post_code_electorate_maps
  # GET /post_code_electorate_maps.json
  def index
    @post_code_electorate_maps = PostCodeElectorateMap.all
  end

  # GET /post_code_electorate_maps/1
  # GET /post_code_electorate_maps/1.json
  def show
  end

  # GET /post_code_electorate_maps/new
  def new
    @post_code_electorate_map = PostCodeElectorateMap.new
  end

  # GET /post_code_electorate_maps/1/edit
  def edit
  end

  # POST /post_code_electorate_maps
  # POST /post_code_electorate_maps.json
  def create
    @post_code_electorate_map = PostCodeElectorateMap.new(post_code_electorate_map_params)

    respond_to do |format|
      if @post_code_electorate_map.save
        format.html { redirect_to @post_code_electorate_map, notice: 'Post code electorate map was successfully created.' }
        format.json { render :show, status: :created, location: @post_code_electorate_map }
      else
        format.html { render :new }
        format.json { render json: @post_code_electorate_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_code_electorate_maps/1
  # PATCH/PUT /post_code_electorate_maps/1.json
  def update
    respond_to do |format|
      if @post_code_electorate_map.update(post_code_electorate_map_params)
        format.html { redirect_to @post_code_electorate_map, notice: 'Post code electorate map was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_code_electorate_map }
      else
        format.html { render :edit }
        format.json { render json: @post_code_electorate_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_code_electorate_maps/1
  # DELETE /post_code_electorate_maps/1.json
  def destroy
    @post_code_electorate_map.destroy
    respond_to do |format|
      format.html { redirect_to post_code_electorate_maps_url, notice: 'Post code electorate map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_code_electorate_map
      @post_code_electorate_map = PostCodeElectorateMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_code_electorate_map_params
      params.require(:post_code_electorate_map).permit(:electorate_id, :post_code_id)
    end
end

app/helpers/post_code_electorate_maps_helper.rb
module PostCodeElectorateMapsHelper
end

app/views/post_code_electorate_maps/_form.html.erb
<%= form_for(@post_code_electorate_map) do |f| %>
  <% if @post_code_electorate_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_code_electorate_map.errors.count, "error") %> prohibited this post_code_electorate_map from being saved:</h2>

      <ul>
      <% @post_code_electorate_map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :electorate_id %><br>
    <%= f.text_field :electorate_id %>
  </div>
  <div class="field">
    <%= f.label :post_code_id %><br>
    <%= f.text_field :post_code_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_code_electorate_maps/edit.html.erb
<h1>Editing Post Code Electorate Map</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_code_electorate_map %> |
<%= link_to 'Back', post_code_electorate_maps_path %>

app/views/post_code_electorate_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Code Electorate Maps</h1>

<table>
  <thead>
    <tr>
      <th>Electorate</th>
      <th>Post code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_code_electorate_maps.each do |post_code_electorate_map| %>
      <tr>
        <td><%= post_code_electorate_map.electorate %></td>
        <td><%= post_code_electorate_map.post_code %></td>
        <td><%= link_to 'Show', post_code_electorate_map %></td>
        <td><%= link_to 'Edit', edit_post_code_electorate_map_path(post_code_electorate_map) %></td>
        <td><%= link_to 'Destroy', post_code_electorate_map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post code electorate map', new_post_code_electorate_map_path %>

app/views/post_code_electorate_maps/new.html.erb
<h1>New Post Code Electorate Map</h1>

<%= render 'form' %>

<%= link_to 'Back', post_code_electorate_maps_path %>

app/views/post_code_electorate_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Electorate:</strong>
  <%= @post_code_electorate_map.electorate %>
</p>

<p>
  <strong>Post code:</strong>
  <%= @post_code_electorate_map.post_code %>
</p>

<%= link_to 'Edit', edit_post_code_electorate_map_path(@post_code_electorate_map) %> |
<%= link_to 'Back', post_code_electorate_maps_path %>